//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOverlay.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad8")]
        public global::System.Windows.Forms.Keys BSFrog {
            get {
                return ((global::System.Windows.Forms.Keys)(this["BSFrog"]));
            }
            set {
                this["BSFrog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad7")]
        public global::System.Windows.Forms.Keys BSWolfs {
            get {
                return ((global::System.Windows.Forms.Keys)(this["BSWolfs"]));
            }
            set {
                this["BSWolfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad4")]
        public global::System.Windows.Forms.Keys BSRaptors {
            get {
                return ((global::System.Windows.Forms.Keys)(this["BSRaptors"]));
            }
            set {
                this["BSRaptors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad1")]
        public global::System.Windows.Forms.Keys BSRocks {
            get {
                return ((global::System.Windows.Forms.Keys)(this["BSRocks"]));
            }
            set {
                this["BSRocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad2")]
        public global::System.Windows.Forms.Keys TSFrog {
            get {
                return ((global::System.Windows.Forms.Keys)(this["TSFrog"]));
            }
            set {
                this["TSFrog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad3")]
        public global::System.Windows.Forms.Keys TSWolfs {
            get {
                return ((global::System.Windows.Forms.Keys)(this["TSWolfs"]));
            }
            set {
                this["TSWolfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad6")]
        public global::System.Windows.Forms.Keys TSRaptors {
            get {
                return ((global::System.Windows.Forms.Keys)(this["TSRaptors"]));
            }
            set {
                this["TSRaptors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad9")]
        public global::System.Windows.Forms.Keys TSRocks {
            get {
                return ((global::System.Windows.Forms.Keys)(this["TSRocks"]));
            }
            set {
                this["TSRocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BSFrogCoords {
            get {
                return ((global::System.Drawing.Point)(this["BSFrogCoords"]));
            }
            set {
                this["BSFrogCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BSWolfsCoords {
            get {
                return ((global::System.Drawing.Point)(this["BSWolfsCoords"]));
            }
            set {
                this["BSWolfsCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BSRaptorsCoords {
            get {
                return ((global::System.Drawing.Point)(this["BSRaptorsCoords"]));
            }
            set {
                this["BSRaptorsCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BSRocksCoords {
            get {
                return ((global::System.Drawing.Point)(this["BSRocksCoords"]));
            }
            set {
                this["BSRocksCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TSFrogCoords {
            get {
                return ((global::System.Drawing.Point)(this["TSFrogCoords"]));
            }
            set {
                this["TSFrogCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TSWolfsCoords {
            get {
                return ((global::System.Drawing.Point)(this["TSWolfsCoords"]));
            }
            set {
                this["TSWolfsCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TSRaptorsCoords {
            get {
                return ((global::System.Drawing.Point)(this["TSRaptorsCoords"]));
            }
            set {
                this["TSRaptorsCoords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TSRocksCoords {
            get {
                return ((global::System.Drawing.Point)(this["TSRocksCoords"]));
            }
            set {
                this["TSRocksCoords"] = value;
            }
        }
    }
}
